### ISSUE TITLE
/bin/bash into the image.

### ISSUE THREAD

**Issue by thomas-vl** [dtroncy/docker-rpi-nzbget#1]
Hi Dtroncy,

Let me start off by brilliant work! Because of you i've got nzbget running in minutes on my Pi!
I tried logging on to the nzbget image by using this command:
docker exec -it nzbget /bin/bash

But it gave me the following error:
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

How do i log in to the image?

Regards,

Thomas

**Comment by dtroncy** [comment]
Hi Thomas,

Thanks for the compliment 👍.

About your error, for more lightness the rpi-nzbget image is based on an alpine image (hypriot/rpi-alpine) that not contained bash.

You can use **ash** or **sh** instead and modify your commande like that :

`docker exec -it nzbget /bin/ash`

`docker exec -it nzbget /bin/sh`

`docker exec -it nzbget ash`

`docker exec -it nzbget sh`

Regards,

Damien
